---
# Shamelessly taken from https://github.com/plicease/Dist-Zilla-PluginBundle-Author-Plicease/blob/master/.appveyor.yml
# Thanks!
install:
    - if not exist C:\libtap mkdir C:\libtap
    - if not exist C:\libtap\strawberry-perl-5.24.0.1-64bit.msi curl -fsS -o C:\libtap\strawberry-perl-5.24.0.1-64bit.msi http://strawberryperl.com/download/5.24.0.1/strawberry-perl-5.24.0.1-64bit.msi
    - if not exist C:\strawberry\perl\bin\perl.exe msiexec /i C:\libtap\strawberry-perl-5.24.0.1-64bit.msi /quiet /qn /norestart /log install.log INSTALLDIR="C:\strawberry"
    - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
    - SET PERL5LIB=C:/_P5/lib/perl5
    - SET PERL_LOCAL_LIB_ROOT=C:/_P5
    - SET PERL_MB_OPT=--install_base C:/_P5
    - SET PERL_MM_OPT=INSTALL_BASE=C:/_P5
    - perl -v
    - cpanm --notest Devel::Trace Task::FreecellSolver::Testing
    - if not exist C:\libtap\gperf-3.0.4.tar.gz curl -fsS -o C:\libtap\gperf-3.0.4.tar.gz http://ftp.gnu.org/pub/gnu/gperf/gperf-3.0.4.tar.gz
build: off
test_script:
    - set CMAKE_MAKE_PROGRAM=C:\strawberry\c\bin\gmake.exe
    - mkdir fc-solve\b
    - cd fc-solve\b
    # Trying this hack to take more precendence for Inline::C / etc.
    - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;C:\_P5\bin;%PATH%
    # - perl ../source/run-tests.pl --glob="hard-disk-offloading-queue*.{py,t}"
    - perl ../source/t/t/hard-disk-offloading-queue.t
cache:
    - C:\libtap
    - C:\_P5
    - C:\strawberry
shallow_clone: true
