---
# Shamelessly taken from https://github.com/plicease/Dist-Zilla-PluginBundle-Author-Plicease/blob/master/.appveyor.yml
# Thanks!
install:
    - choco install ag
    - if not exist C:\libtap mkdir C:\libtap
    - if not exist C:\libtap\strawberry-perl-5.24.0.1-64bit.msi curl -fsS -o C:\libtap\strawberry-perl-5.24.0.1-64bit.msi http://strawberryperl.com/download/5.24.0.1/strawberry-perl-5.24.0.1-64bit.msi
    - if not exist C:\strawberry\perl\bin\perl.exe msiexec /i C:\libtap\strawberry-perl-5.24.0.1-64bit.msi /quiet /qn /norestart /log install.log INSTALLDIR="C:\strawberry"
    - copy c:\Python35-x64\python.exe c:\Python35-x64\python3.exe
    - SET PATH=C:\Python35-x64;C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
    - python3 -mpip install random2
    - perl -v
    - copy C:\msys64\mingw64\bin\mingw32-make.exe C:\msys64\mingw64\bin\make.exe
    - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
    - SET PERL5LIB=C:/_P5/lib/perl5
    - SET PERL_LOCAL_LIB_ROOT=C:/_P5
    - SET PERL_MB_OPT=--install_base C:/_P5
    - SET PERL_MM_OPT=INSTALL_BASE=C:/_P5
    - perl -v
    - cpanm --notest Devel::Trace Task::FreecellSolver::Testing
    - hg clone https://bitbucket.org/shlomif/shlomif-cmake-modules fc-solve/source/cmake/sfc
    - copy fc-solve\source\cmake\sfc\shlomif-cmake-modules\Shlomif_Common.cmake fc-solve\source\cmake\
    - git clone -b make-code-suitable-for-fc-solve git://github.com/shlomif/patsolve.git fc-solve/source/patsolve-shlomif
    - if not exist C:\libtap\gperf-3.0.4.tar.gz curl -fsS -o C:\libtap\gperf-3.0.4.tar.gz http://ftp.gnu.org/pub/gnu/gperf/gperf-3.0.4.tar.gz
    - copy C:\libtap\gperf-3.0.4.tar.gz .
    - tar -xvf gperf-3.0.4.tar.gz
    - cd gperf-3.0.4 && perl -e "if (-e qq#C:\\libtap\\bin\\gperf.exe#) { exit(0); } $ENV{PATH} = qq#C:\\msys64\\mingw64\\bin;$ENV{PATH}#; system('sh configure --prefix=C:/libtap') or system('gmake') or system('gmake install');" && cd ..
    - git clone -b cmake https://github.com/shlomif/libtap
    - mkdir libtap\b
    - cd libtap\b
    - set CMAKE_MAKE_PROGRAM=C:\strawberry\c\bin\gmake.exe
    - cmake -G "MinGW Makefiles" -DCMAKE_MAKE_PROGRAM=%CMAKE_MAKE_PROGRAM% -DCMAKE_INSTALL_PREFIX=C:\libtap ..
    - echo %PATH%
    - gmake
    - gmake install
    - cd ..\..\
build: off
test_script:
    - set CMAKE_MAKE_PROGRAM=C:\strawberry\c\bin\gmake.exe
    - set LIBRARY_PATH=C:\libtap\lib
    - set CMAKE_LIBRARY_PATH=C:\libtap\lib
    - set LD_LIBRARY_PATH=C:\libtap\lib
    - set CPATH=C:\libtap\include
    - set PATH=C:\libtap\bin;%PATH%
    - set HARNESS_BREAK=1
    - set FCS_USE_TEST_RUN=1
    - mkdir fc-solve\b
    - cd fc-solve\b
    - perl ../source/Tatzer -G "MinGW Makefiles"
    - SET PATH=C:\projects\fc-solve\fc-solve\scripts\win32;%PATH%
    - echo %PATH%
    - gmake
    - gmake boards
    # Trying this hack to take more precendence for Inline::C / etc.
    - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;C:\_P5\bin;%PATH%
    - perl ../source/run-tests.pl --glob="hard-disk-offloading-queue*.{py,t}"
cache:
    - C:\libtap
    - C:\_P5
    - C:\strawberry
shallow_clone: true
